# Generated by Django 4.0.3 on 2022-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title1',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
