# Generated by Django 4.0.3 on 2022-05-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title1',
            new_name='discription',
        ),
    ]
