# Generated by Django 4.0.3 on 2022-05-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_title1_todo_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date',
        ),
    ]
