# Generated by Django 4.0.3 on 2022-05-03 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_todo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time1',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
